version: 2
updates:
- package-ecosystem: maven
  directory: "/reactive-java"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.reactivex.rxjava2:rxjava
    versions:
    - 2.2.20
